version: '3'

services:

  base_app:
    # image: bwnimages.azurecr.io/egovcore/app:developemnt
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      # Source code
      - ./app/src:/src
      - ./app/scripts:/scripts
      # Static and media
      - media_files:/mnt/storage/media
      - static_files:/mnt/storage/static
    env_file:
      - ./config/.env
    command: sh /scripts/runserver.sh
    restart: on-failure

  base_nginx:
    image: nginx:stable
    env_file:
      - ./config/.env
    volumes:
      # Configuration
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/includes:/etc/nginx/includes
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      # Static and media
      - media_files:/mnt/storage/media
      - static_files:/mnt/storage/static
    restart: on-failure
